name: Daily Feedback Analysis

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 5 AM UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Analysis
      run: |
        curl -X POST ${{ secrets.VERCEL_URL }}/api/run-analysis \
        -H "Authorization: Bearer ${{ secrets.ANALYSIS_API_KEY }}" \
        -H "Content-Type: application/json"